"""create core tables

Revision ID: b89f43a218eb
Revises: 
Create Date: 2026-03-12 15:09:12.505882

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'b89f43a218eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
